Adapt `NetworkPolicy`s
gardener/gardener-extension-shoot-oidc-service pull request #111
Opened 2023-05-10 13:46 UTC by rfranzke

**How to categorize this PR?**

/area security networking
/kind enhancement
/platform aws

**What this PR does / why we need it**:
This PR adapts the `NetworkPolicy`s as following:

- The `oidc-webhook-authenticator` `Service` is now annotated with `networking.resources.gardener.cloud/from-all-webhook-targets-allowed-ports` to allow it being reached from the `kube-apiserver` of shoots (see https://github.com/gardener/gardener/pull/7907). The webhook mutating the pod labels of the `kube-apiserver` is deprecated and can be cleaned up in a future release.
- The custom pod label selectors for Prometheus is adapted similar to https://github.com/gardener/gardener/pull/7907/commits/b14706780cb74902404aa44351bd39124aee48ae.

**Which issue(s) this PR fixes**:
Related to https://github.com/gardener/gardener/issues/7352

**Release note**:

```other operator
NONE
```

2023-05-10 14:25 UTC, dimityrmirchev requested changes
Thanks! I will probably test this tomorrow, but one question after a quick first look.

2023-05-10 14:25 UTC, dimityrmirchev commented on charts/gardener-extension-shoot-oidc-service/templates/service.yaml
> +    networking.resources.gardener.cloud/from-world-to-ports: '[{"protocol":"TCP","port":{{ .Values.webhookConfig.serverPort }}}]'
Maybe I am missing something, but isn't this label still needed (the server port)? I do not see it removed in other PRs. Maybe you meant to change the labels regarding the `metrics` port? See [this](https://github.com/gardener/gardener/commit/b14706780cb74902404aa44351bd39124aee48ae#diff-0f942ac1144b309bca6a3b86b204f6a3e3daa1877a9651e1c3d291f121b72927L8-L9) as an example.

2023-05-11 13:44 UTC, dimityrmirchev requested changes
Thanks! I think we need one more change. The other looks good

2023-05-11 13:44 UTC, dimityrmirchev commented on charts/gardener-extension-shoot-oidc-service/templates/service.yaml
> +    networking.resources.gardener.cloud/from-all-seed-scrape-targets-to-ports: '[{"protocol":"TCP","port":{{ .Values.webhookConfig.serverPort }}}]'
```suggestion
    networking.resources.gardener.cloud/from-all-seed-scrape-targets-to-ports: '[{"protocol":"TCP","port":{{ .Values.metrics.port }}}]'
```

I guess this should also be changed

2023-05-16 08:20 UTC, dimityrmirchev approved these changes
/lgtm

2023-05-16 08:20 UTC, merged

2023-06-12 16:30 UTC, rfranzke commented
When do you plan the next release containing this PR?

2023-06-13 06:55 UTC, dimityrmirchev commented
I will release it later today