Drop support for Shoots with Kubernetes version <= 1.26
gardener/gardener-extension-shoot-oidc-service pull request #253
Opened 2024-10-31 07:11 UTC by RadaBDimitrova

**How to categorize this PR?**

/kind cleanup

**What this PR does / why we need it**:
- Adapt PDBs to use unhealthyPodEvictionPolicy: AlwaysAllow unconditionally
- Drop support for Shoots, Seeds and Gardens with Kubernetes version <= 1.26.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/10339

**Special notes for your reviewer**:
In draft until the gardener/gardener PR is merged and released.

**Release note**:

```other operator
`extension-shoot-oidc-service` no longer supports Shoots with Кubernetes version <= 1.26.
```

2025-03-04 14:24 UTC, dimityrmirchev requested changes
Thank you! 
Two minor nits, other looks good.

2025-03-04 14:24 UTC, dimityrmirchev commented on charts/gardener-extension-shoot-oidc-service/templates/poddisruptionbudget.yaml
> +  unhealthyPodEvictionPolicy: AlwaysAllow
Please add a new line at the end of file.

2025-03-04 14:24 UTC, dimityrmirchev commented on pkg/controller/lifecycle/actuator.go
> -func buildPDB(namespace string, k8sVersion *semver.Version) client.Object {
We no longer need this function, we can directly inline the PDB

2025-03-04 15:03 UTC, dimityrmirchev submitted a review, later dismissed
/lgtm

2025-03-05 09:59 UTC, ialidzhikov commented on test/system/lifecycle/lifecycle_test.go
This could be removed. No need to check `err` after we removed the line that could return error.

```suggestion
```

2025-03-06 09:06 UTC, ialidzhikov requested changes

2025-03-06 09:06 UTC, ialidzhikov commented on test/system/lifecycle/lifecycle_test.go
> -		By("Verify that PodDisruptionBudget is correctly configured")
This `By` still makes sense. Can we please preserve it?

2025-03-06 10:17 UTC, ialidzhikov approved these changes
/lgtm

2025-03-07 09:38 UTC, dimityrmirchev approved these changes
Thank you both @RadaBDimitrova and @ialidzhikov !

/lgtm

2025-03-07 09:38 UTC, merged